### PR TITLE
WordPress 5.5.0 compatible

### PR DESCRIPTION
**Pull request by jhhazelaar**
Wordpress 5.5 compatible fix. 

Fixing #6

### CODE REVIEW

**Comment by Log1x** [comment]
Thanks for this.

Does https://github.com/Log1x/wp-smtp/blob/4dca46539fe1a687fa87fcbce8dd514481005eb0/src/SMTP.php#L202 need modified at all for the new namespace?

**Comment by jhhazelaar** [comment]
I don't know need to test it.

**Comment by tangrufus** [comment]
Yes for the exception namespace because it is now under `namespace PHPMailer\PHPMailer;` 

See: 
- https://github.com/WordPress/wordpress-develop/blob/220a6cc80510b1f0e6e09520c5ac999208f13d27/src/wp-includes/PHPMailer/PHPMailer.php#L1973
- https://github.com/WordPress/wordpress-develop/blob/220a6cc80510b1f0e6e09520c5ac999208f13d27/src/wp-includes/PHPMailer/Exception.php#L22

**Comment by tim-field** [comment]
Can we get this merged ?

**Pull request merged**
